site_name: ADMINISTRACIÓ DE SISTEMES OPERATIUS
theme:
  logo: linux-ethandud.gif
  name: material
  custom_dir: docs/custom
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.download
    - footer.hide
    - palette.toggle
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - Welcome: index.md

include:
  - assets/css/custom.css
